### ISSUE TITLE
Osc: Adding math channels over the limit

### ISSUE THREAD

**Issue by DanielGuramulta** [analogdevicesinc/scopy#127]
1) When the limit is reached the math panel would close but clicking on the btnSettings would open it again:
![osc_quickfix1](https://user-images.githubusercontent.com/26142210/27184434-d509f326-51ea-11e7-9536-ecf4478683cb.png)
2) When the limit is reached, but we click multiple times on the add math channel button in the math panel the limit will be exceeded:
![osc_quickfix2](https://user-images.githubusercontent.com/26142210/27184486-fd8e3cee-51ea-11e7-81cc-37ae90730102.png)

**Comment by DanielGuramulta** [comment]
This commit should solve the first issue: https://github.com/analogdevicesinc/scopy/commit/c9fdf1b5ff5cc8cd83fa5d2c26136f3ff0e58020
This one should solve the second: https://github.com/analogdevicesinc/scopy/commit/1c12c805cbdc5ddacb6a1859212bb088c1c2f8b2

**Comment by pcercuei** [comment]
The first commit doesn't fix the problem. The panel doesn't open up, but the channel settings option button is shown as pressed.

**Comment by pcercuei** [comment]
You can fix the two with a simpler change: https://gist.github.com/pcercuei/375334314e11a1756acdcfd2fa2de693
