### ISSUE TITLE
Can't increase duty cycle value, it is stuck

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#271]
Scopy Build: 

Steps to reproduce

Enable DIO0
Set duty cycle to 0.
Set clock frequency to any of the following:
- 3 MHz	
- 6-7 MHz
- 9 MHz 
- 11-15 MHz				
- 18-19 MHz					
- 21-24 MHz					
- 26-30 MHz			
- 33-34 MHz
- 36 MHz
- 38 MHz
- 42 MHz
- 44 MHz
- 46-49 MHz

For example, 3 MHz.		
Then click + to increase duty cycle.
The value is stuck at 3. It does not increase further. The same as with the other mentioned frequency.

![b](https://user-images.githubusercontent.com/25096080/30677766-4d91dbde-9ec0-11e7-87e1-c705fb5f361e.PNG)

**Comment by adisuciu** [comment]
Fixed with cdeab7f07118c2367adbc8c9e65a87a2f6617b98

**Comment by amiclaus** [comment]
From my point of view, on 8f7e63f (v0.8), this bug partially fixed: if using the fine mode in order to increase the duty cycle, the value remains stuck. This happens due to the small nr. of samples available on each period of the signal and implicitly the duty cycle values available is reduced. Therefore, from the design point of view, something should be made: either make the fine mode unavailable in this kind of situation, either coarse mode and fine mode have the same behavior.

**Comment by amiclaus** [comment]
On Scopy build: c8ad583 (v0.9) the bug is fixed.
