### ISSUE TITLE
One period not displayed at max frequency

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#314]
Scopy build: c8ad583
Use only CH1. (Disable CH2)
Use Square Wave.
Start i.e. from 1kHz frequency.
Press "+" button for the frequency until reaches max frequency. At 37.5MHz on the plot there is not displayed an entire period.
![image](https://user-images.githubusercontent.com/26061529/33067030-96691460-ceb5-11e7-90cd-e3115e0611a0.png)

**Comment by adisuciu** [comment]
Fixed with  b33fb00

**Comment by amiclaus** [comment]
The bug still persists on 92484c8 v(0.10).

Start from 1kHz, and keep the "+ button pressed" until reaches 37.5MHz.

Sometimes, the procedure must be repeated to see the bug.

![image](https://user-images.githubusercontent.com/26061529/35163607-00bb44b4-fd50-11e7-9fea-b0d16aba35a1.png)

**Comment by adisuciu** [comment]
Fixed with  3406832

**Comment by amiclaus** [comment]
On Scopy build: 08b2360 the bug is fixed.
