### ISSUE TITLE
Selected marker enhancement

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#383]
I think that is more intuitive to have the selected marker yellow filled. 
See pic (M2 is selected, M1 is yellow filled).
![image](https://user-images.githubusercontent.com/26061529/36905865-16b39434-1e3d-11e8-86d6-795f406387ef.png)

**Comment by adisuciu** [comment]
Fixed with https://github.com/analogdevicesinc/scopy/commit/54a986c641ff8ed8068452140b92db2a6f9d375b

**Comment by amiclaus** [comment]
On Scopy build: 6bd7075 (v0.11) the selected marker is still not yellow filled. (see pic: m2 selected, m1 yellow filled)

![image](https://user-images.githubusercontent.com/26061529/37277645-fee74e78-25ed-11e8-990c-bed21ea1e362.png)

**Comment by adisuciu** [comment]
I think the color is a matter of preference. We can review this when we review the UI.
