### ISSUE TITLE
Signal Generator: Phase setting in ns, ns, us, ms and s automatically changes.

### ISSUE THREAD

**Issue by drbautista** [analogdevicesinc/scopy#384]
OS: Windows 10 64bit
Scopy Version: 0bc041b
Firmware Version: v0.18

Steps to reproduce:

1. Open Signal Generator
2. Set both channels to Amplitude 5V, Frequency: 1.25MHz, Offset: 0V, Phase: 0 degrees
3. On Channel 1, Set Phase: 400ns [the graphic representation should be similar to 180 degrees phase shift]
4.  Check channel 2's setting and the phase shift will also be set to 400ns.
5. Go back to channel 1's setting and the phase shift will change again.

The attached photo shows the chronological order of the above's step.

![phase shift in seconds](https://user-images.githubusercontent.com/20266602/36961543-e0c4d012-2086-11e8-8ab7-4d7682fff38c.png)

I also tested it on different frequency and different phase setting.

**Comment by septimiusarca** [comment]
Fixed with [095ed7b](https://github.com/analogdevicesinc/scopy/pull/392/commits/095ed7b0c046b3ae685a75f9ead6fc543212f516)

**Comment by amiclaus** [comment]
Following the steps after a Scopy reset shows that the bug is not fixed.

**Comment by adisuciu** [comment]
Should be fixed now : https://github.com/analogdevicesinc/scopy/pull/398

**Comment by amiclaus** [comment]
On Scopy build: 1a38185 the bug is fixed.
