### ISSUE TITLE
Signal Generator: Waveform type always loads sinewave on channel 1

### ISSUE THREAD

**Issue by drbautista** [analogdevicesinc/scopy#412]
OS: Windows 10 64bit
 Scopy Version: f2c402a
 Firmware Version: v0.19

Steps to reproduce:

1. Set Channel 1's waveform type to square wave. and channel 2 to triangle wave.
2. Set different amplitude, offset, frequency and phase.
3. Save profile.
4. Reset Scopy on preference menu.
5. Load the previously saved profile.

Channel 1's waveform type is always returning to sinewave.
The bug on channel 2's waveform type is not always present.

**Comment by claudiupop** [comment]
Should be fixed with commit 1bfadf59419d5da2f516b40a05f8b5c56f36c1bb

**Comment by amiclaus** [comment]
The bug is partially fixed, excepting the number of periods displayed.
![image](https://user-images.githubusercontent.com/26061529/39514573-38954c9e-4e00-11e8-8cd5-9d7f439b0958.png)

**Comment by claudiupop** [comment]
This should be fixed with f0b2eaa48607416f517a4ceb5bdb8d57cd5284c0

**Comment by amiclaus** [comment]
On Scopy build: 5af87b4 (v0.12) the bug is fixed.
