### ISSUE TITLE
Value becomes 0 when attempting to change unit in phase

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#676]
Scopy version: 4fe815a0
firmware verson: v0.23

Steps to reproduce:

Set frequency to 500 Hz, sine wave
Set phase to 0 deg
Then change the unit to ms, then add value 1.5 ms, then enter
Then change unit again to degree, when attempting to change the unit to degree the value will become 0. See screen  recording
![bug1](https://user-images.githubusercontent.com/25096080/63238142-8d5ba100-c277-11e9-9289-608c5220d6ee.gif)

**Comment by DanielGuramulta** [comment]
Should be fixed with: #692

**Comment by amiclaus** [comment]
On Scopy build: 33b6c1c (v1.1.0) the bug still persists.
OS: Windows 10, 64-bit

**Comment by DanielGuramulta** [comment]
I fix an error made in: #692 with #695. From what I tested it looks fixed to me. Can you look again into the issue and confirm that the problem is solved this time?

Thank you!

**Comment by amiclaus** [comment]
On Scopy build: 214c48 (v1.10) the bug is fixed.
