### ISSUE TITLE
Pattern Generator: changing parameters of a channel affects the signal generated on another channel

### ISSUE THREAD

**Issue by andreeaipop** [analogdevicesinc/scopy#714]
OS Version: Windows 10 (10.0)
FW Version: v 0.24
SW Version: 6fa2c03

**Describe the bug**
Changing the settings of a high frequency signal in pattern generator affects the signal generated on another channel (at a significant smaller frequency value).

Open Scopy Pattern generator and enable 2 random digital channels, one with low frequency and one with high frequency.
 Configure one channel ( DIO6 in this case) to 50 Hz frequency and 50% Duty cycle.
Configure the second channel (DIO8) to 1Mhz and 50% Duty cycle.
If you change the frequency of the second channel to certain values (3 Mhz, 4Mhz, 7 Mhz, 16Mhz ...) pattern generator automatically adjuts the duty cycle of the channel, but also affects the signal generated on the lower frequency channel.

**Expected behavior**
Changing the parameters of one digital channel should not affect the signal on another digital channel.

**Screenshots**
This is how th 50Hz signal (DIO6) and 1 Mhz signal (DIO8) look in logic analyzer:
![logic_1](https://user-images.githubusercontent.com/52502092/65326201-9a8ee700-dbb9-11e9-819e-fff1f0df94d4.PNG)
Change the frequency of DIO8 to 3 Mhz:
![pattern_gen](https://user-images.githubusercontent.com/52502092/65326169-821ecc80-dbb9-11e9-8098-ab69fad058c7.gif)

The signals will look like this even if nothing was changed from the settngs of DIO6
![logic_2](https://user-images.githubusercontent.com/52502092/65326212-a11d5e80-dbb9-11e9-9a70-fa6e8c62ba9e.PNG)

**Comment by DanielGuramulta** [comment]
Issue mentioned in #949 solved with #971

**Comment by tagoylo** [comment]
Issue still exists on Scopy v1.3 build 441fd193.
![image](https://user-images.githubusercontent.com/25096080/113817135-6cc3c000-97a8-11eb-88c3-38460fe11627.png)
![image](https://user-images.githubusercontent.com/25096080/113817058-49991080-97a8-11eb-93df-5cafee0aecce.png)

**Comment by adisuciu** [comment]
This cannot be fixed due to the way hardware works. We put a warning in the pattern generator when this happens - "Maximum buffer size reached"
-Adrian

**Comment by tagoylo** [comment]
Got it. When the warning occurs, this is expected. Will close this item.
